begin;
select no_plan();
insert into auth.users(id) values ('81000000-0000-4000-8000-000000000001'),('81000000-0000-4000-8000-000000000002');
select public.assign_profile_role('81000000-0000-4000-8000-000000000001','editor');
create temp table choice_checks(kind text primary key,id uuid);
grant all on choice_checks to authenticated;
set local role authenticated;
select set_config('request.jwt.claims','{"sub":"81000000-0000-4000-8000-000000000002","role":"authenticated"}',true);
select throws_ok($$select public.admin_catalogue_choice('brands','Denied test brand')$$,'42501','Admin access denied','ordinary account denied');
select set_config('request.jwt.claims','{"sub":"81000000-0000-4000-8000-000000000001","role":"authenticated"}',true);
insert into choice_checks select 'brands',(public.admin_catalogue_choice('brands','  Synthetic   test brand ')->>'id')::uuid;
insert into choice_checks select 'specialties',(public.admin_catalogue_choice('specialties','  Synthetic   test specialty ')->>'id')::uuid;
select is((public.admin_catalogue_choice('brands','SYNTHETIC test BRAND')->>'id')::uuid,(select id from choice_checks where kind='brands'),'case and whitespace retries reuse brand');
select is((public.admin_catalogue_choice('specialties','synthetic test specialty')->>'id')::uuid,(select id from choice_checks where kind='specialties'),'retries reuse specialty');
select ok(public.admin_shop_options()->'brands' @> jsonb_build_array(jsonb_build_object('id',(select id from choice_checks where kind='brands'),'label','Synthetic test brand')),'created brand is selectable');
select ok(public.admin_shop_options()->'specialties' @> jsonb_build_array(jsonb_build_object('id',(select id from choice_checks where kind='specialties'),'label','Synthetic test specialty')),'created specialty is selectable');
select throws_ok($$select public.admin_catalogue_choice('shops','Not allowed')$$,'22023','Invalid choice','no arbitrary table writes');
select throws_ok($$select public.admin_catalogue_choice('brands',repeat('a',301))$$,'22023','Invalid choice','bounded names');
select throws_ok($$select public.admin_catalogue_choice('brands','   ')$$,'22023','Invalid choice','blank name denied');
select throws_ok($$insert into public.brands(slug,name) values('bypass','Bypass')$$,'42501',null,'direct authenticated writes remain denied');
reset role;
select is((select count(*) from public.admin_audit_log where entity_id in(select id from choice_checks) and action='catalogue_insert'),2::bigint,'one audit per creation, none for reuse');
select ok((select bool_and(actor_user_id='81000000-0000-4000-8000-000000000001') from public.admin_audit_log where entity_id in(select id from choice_checks)),'actual editor audited');
select ok(not exists(select 1 from public.shop_brands where brand_id=(select id from choice_checks where kind='brands')),'choice creation does not attach or publish a shop');
select ok(not exists(select 1 from public.shop_specialties where specialty_id=(select id from choice_checks where kind='specialties')),'specialty creation does not attach a shop');
update public.profiles set role='user' where id='81000000-0000-4000-8000-000000000001';
set local role authenticated;
select throws_ok($$select public.admin_catalogue_choice('brands','After revocation')$$,'42501','Admin access denied','live role revocation enforced');
reset role;
set local role anon;
select throws_ok($$select public.admin_catalogue_choice('brands','Anonymous')$$,'42501',null,'anon execute denied');
reset role;
select * from finish();
rollback;
