import { fireEvent, render, screen, waitFor } from '@testing-library/react';
import { afterEach, expect, it, vi } from 'vitest';
import { ImportAdmin } from './ImportAdmin';
import { VERSION } from './contract';
vi.mock('@/src/features/account/AccountSessionProvider', () => ({ useAccountSession: () => ({ session: { status: 'signed-in', userId: '70000000-0000-4000-8000-000000000001' } }) }));
afterEach(() => vi.unstubAllGlobals());
it('uses the app shell landmark, names controls accessibly and invalidates changed input', async () => {
  const options = { localities: [], types: [], brands: [], specialties: [], services: [] };
  vi.stubGlobal('fetch', vi.fn(async (_url, init) => String(_url).includes('/batches') ? Response.json([]) : Response.json(init?.method === 'POST' ? { version: VERSION, rows: [{ rowId: 'line-2', line: 2, name: 'Synthetic', action: 'new_private_draft', targetId: null, revision: null, issues: [], candidates: [], fileDuplicates: [], changes: [], publicationErrors: [], hasPrivateChanges: false }] } : { options })));
  render(<main><ImportAdmin /></main>);
  const input = await screen.findByLabelText('CSV or JSON file');
  expect(screen.getAllByRole('main')).toHaveLength(1);
  fireEvent.change(input, { target: { files: [{ name: 'synthetic.csv', size: 15, arrayBuffer: async () => new TextEncoder().encode('name\nSynthetic').buffer }] } });
  const preview = await screen.findByRole('button', { name: 'Run dry-run preview' });
  expect(screen.getByRole('combobox', { name: 'name' })).toBeInTheDocument();
  fireEvent.click(preview);
  const filter = await screen.findByRole('combobox', { name: 'Show' });
  expect(screen.getByLabelText('Show', { exact: true })).toBe(filter);
  expect(screen.getByRole('textbox', { name: 'Find row or shop' })).toBeInTheDocument();
  fireEvent.change(filter, { target: { value: 'blocked' } });
  expect(screen.getByText(/0 matching rows/)).toBeInTheDocument();
  fireEvent.change(screen.getByLabelText('name', { exact: true }), { target: { value: 'short_description' } });
  await waitFor(() => expect(screen.queryByRole('heading', { name: 'Preview results' })).not.toBeInTheDocument());
});

it('shows the loaded filename, replaces it and clears it when starting a new batch', async () => {
  vi.stubGlobal('fetch', vi.fn(async () => Response.json({ options: { localities: [], types: [], brands: [], specialties: [], services: [] } })));
  render(<ImportAdmin />);
  const input = await screen.findByLabelText('CSV or JSON file') as HTMLInputElement;
  const choose = (name: string, content: string) => fireEvent.change(input, { target: { files: [{ name, size: content.length, arrayBuffer: async () => new TextEncoder().encode(content).buffer }] } });
  expect(screen.getByText('No file chosen')).toBeInTheDocument();
  choose('first.csv', 'name\nFirst');
  await screen.findByText('first.csv');
  expect(screen.queryByText('No file chosen')).not.toBeInTheDocument();
  choose('second.csv', 'name\nSecond');
  await screen.findByText('second.csv');
  expect(screen.queryByText('first.csv')).not.toBeInTheDocument();
  fireEvent.click(screen.getByRole('button', { name: 'Start a separate new batch' }));
  expect(screen.getByText('No file chosen')).toBeInTheDocument();
  expect(screen.queryByRole('heading', { name: '2. Match your columns' })).not.toBeInTheDocument();
  choose('second.csv', 'name\nSecond');
  await screen.findByText('second.csv');
});

it('keeps a rejected filename beside its error and clears an in-flight local read safely',async()=>{
  vi.stubGlobal('fetch',vi.fn(async()=>Response.json({options:{localities:[],types:[],brands:[],specialties:[],services:[]}})));
  render(<ImportAdmin />);
  const input=await screen.findByLabelText('CSV or JSON file');
  fireEvent.change(input,{target:{files:[{name:'wrong.jpg',size:10}]}});
  expect(await screen.findByRole('alert')).toHaveTextContent('Choose a .csv or .json file.');
  expect(screen.getByText('wrong.jpg')).toBeInTheDocument();
  expect(input).toHaveAttribute('aria-invalid','true');
  let finish!:(bytes:ArrayBuffer)=>void;
  fireEvent.change(input,{target:{files:[{name:'slow.csv',size:10,arrayBuffer:()=>new Promise<ArrayBuffer>(resolve=>{finish=resolve;})}]}});
  fireEvent.click(screen.getByRole('button',{name:'Clear selected file'}));
  finish(new TextEncoder().encode('name\nSynthetic').buffer);
  await waitFor(()=>expect(screen.getByText('No file chosen')).toBeInTheDocument());
  expect(screen.queryByRole('heading',{name:'2. Match your columns'})).not.toBeInTheDocument();
  expect(screen.queryByRole('alert')).not.toBeInTheDocument();
});
